version: "3"

services:
  fnet-api:
    # image: ghcr.io/fgfnet/fnet
    build: .
    container_name: fnet-api
    volumes:
      - ./data/django:/data
    ports:
      - "8000:8000"
    depends_on:
      - fnet-mysql
    environment:
      - MYSQL_DATABASE=fnet
      - MYSQL_USER=fnet
      - MYSQL_PASSWORD=fnet
      - DJANGO_SUPERUSER_NAME=root
      - DJANGO_SUPERUSER_PASSWORD=rootroot

  fnet-mysql:
    image: mysql
    container_name: fnet-mysql
    # ports:
    #   - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=fnet
      - MYSQL_USER=fnet
      - MYSQL_PASSWORD=fnet
