# Generated by Django 3.2.10 on 2025-02-16 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshman', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freshman',
            name='department',
            field=models.CharField(choices=[('NC', '자연과학계열'), ('EN', '공학계열'), ('SS', '사회과학계열'), ('HS', '인문과학계열'), ('IN', '자유전공계열')], max_length=10),
        ),
    ]
