# Generated by Django 3.2.10 on 2023-02-12 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(db_column='todo_id', primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=100)),
                ('common', models.BooleanField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Todo_check',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('check', models.BooleanField()),
                ('fg_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fg_id', to=settings.AUTH_USER_MODEL)),
                ('todo_id', models.ForeignKey(db_column='todo_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todo_id', to='todo.todo')),
            ],
        ),
    ]
