# Generated by Django 3.2.10 on 2023-02-14 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='todo',
            table='todo',
        ),
        migrations.AlterModelTable(
            name='todo_check',
            table='todo_check',
        ),
    ]
