# Generated by Django 3.2.10 on 2022-12-14 04:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('student_id', models.CharField(max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(10)])),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('OB', 'OB'), ('Active', 'Active')], default='Active', max_length=10)),
                ('campus', models.CharField(default='n', max_length=10)),
            ],
            options={
                'db_table': 'fg',
                'ordering': ['name'],
            },
        ),
    ]
